export { claudeCodeAdapter } from "./adapters/claude-code/adapter"
export { type CompiledProject, type CompiledRule, compile, type Diagnostic } from "./core/compile/compile"
export { renderAgentText } from "./core/delivery/render-agent"
export { perRule } from "./core/detection/per-rule"
export { createRegistry, type DetectorRegistry } from "./core/detection/registry"
export { type PipelineOptions, type PipelineResult, runPipeline } from "./core/pipeline"
export type * from "./core/types"
export { emptyDelivery } from "./core/types"
export { builtinDetectors } from "./detectors"
