import { existsSync } from "node:fs"
import { mkdir, rm, writeFile } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { rewriteLinks } from "./links"
import { assertPlaced, exampleBinding, FRAGMENTS, PAGES, type Page, pageParts, readme } from "./sources"

/**
 * Writes the generated pages into src/content/docs and the README fragments into src/generated.
 * Both are gitignored and rewritten by every `dev` and `build`: the source is README.md and agents/,
 * and a page that only exists after a build is never stale.
 */
const siteDir = fileURLToPath(new URL("../", import.meta.url))
const docsDir = path.join(siteDir, "src/content/docs")
const generatedDir = path.join(siteDir, "src/generated")

const HEADER = "<!-- Generated by packages/site/scripts/sync.ts from the repository's Markdown. Do not edit. -->"

function frontmatter(page: Page): string {
  return `---\ntitle: ${JSON.stringify(page.title)}\ndescription: ${JSON.stringify(page.description)}\n---\n`
}

export async function sync(): Promise<string[]> {
  const sections = readme()
  assertPlaced(sections)
  exampleBinding(sections)
  const written: string[] = []
  await rm(generatedDir, { recursive: true, force: true })
  await mkdir(generatedDir, { recursive: true })
  for (const page of PAGES) {
    if ("hand" in page.source) {
      const file = path.join(docsDir, `${page.route}.mdx`)
      if (!existsSync(file)) throw new Error(`hand-written page ${page.route} has no ${path.relative(siteDir, file)}`)
      continue
    }
    const body = pageParts(page, sections)
      .map((part) => rewriteLinks(part.markdown, part.source))
      .join("\n\n")
    const file = path.join(docsDir, `${page.route}.md`)
    await mkdir(path.dirname(file), { recursive: true })
    await writeFile(file, `${frontmatter(page)}\n${HEADER}\n\n${body}\n`)
    written.push(file)
  }
  for (const [name, heading] of Object.entries(FRAGMENTS)) {
    const file = path.join(generatedDir, `${name}.md`)
    await writeFile(file, `${rewriteLinks(sections.get(heading) ?? "", "README.md")}\n`)
    written.push(file)
  }
  return written
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const written = await sync()
  process.stdout.write(`wrote ${written.length} files from README.md and agents/\n`)
}
