import { readdir, readFile } from "node:fs/promises"
import path from "node:path"
import { parse, stringify } from "yaml"

export const MANIFEST_HEADER =
  "# Generated by `pnpm manifest` from packages/rules-*/rules.yaml. Do not edit by hand.\n\n"

const RULE_PACKAGE = /^rules-([a-z0-9-]+)$/

type JsonObject = Record<string, unknown>

const isObject = (value: unknown): value is JsonObject =>
  typeof value === "object" && value !== null && !Array.isArray(value)

/** "rules-general" publishes ids as they are; "rules-python" publishes them under "python/". */
export function idPrefix(dir: string): string {
  const name = RULE_PACKAGE.exec(dir)?.[1]
  if (name === undefined) throw new Error(`${dir} is not a rule package`)
  return name === "general" ? "" : `${name}/`
}

function rewritePath(value: string, base: string): string {
  return value.startsWith("@") ? `@${path.posix.join(base, value.slice(1))}` : value
}

function rewriteReference(reference: unknown, base: string): unknown {
  if (typeof reference === "string") return rewritePath(reference, base)
  if (isObject(reference) && typeof reference.path === "string") {
    return { ...reference, path: rewritePath(reference.path, base) }
  }
  return reference
}

/** A package rule as the root manifest publishes it; key order is kept. */
function publish(rule: JsonObject, id: string, prefix: string, base: string): JsonObject {
  return {
    ...rule,
    id: `${prefix}${id}`,
    ...(typeof rule.alias === "string" ? { alias: `${prefix}${rule.alias}` } : {}),
    ...(Array.isArray(rule.context)
      ? { context: rule.context.map((reference) => rewriteReference(reference, base)) }
      : {}),
  }
}

/** The root manifest of the rulecast repository, built from every packages/rules-* package. */
export async function generateManifest(repoRoot: string): Promise<string> {
  const entries = await readdir(path.join(repoRoot, "packages"), { withFileTypes: true })
  const dirs = entries
    .filter((entry) => entry.isDirectory() && RULE_PACKAGE.test(entry.name))
    .map((entry) => entry.name)
    .sort()
  const rules: JsonObject[] = []
  for (const dir of dirs) {
    const base = `packages/${dir}`
    const source = `${base}/rules.yaml`
    const data: unknown = parse(await readFile(path.join(repoRoot, source), "utf8"))
    if (!Array.isArray(data)) throw new Error(`${source}: must be a list of rules`)
    for (const [index, rule] of data.entries()) {
      const id = isObject(rule) ? rule.id : undefined
      if (!isObject(rule) || typeof id !== "string") throw new Error(`${source}: rule ${index + 1} has no id`)
      rules.push(publish(rule, id, idPrefix(dir), base))
    }
  }
  return MANIFEST_HEADER + stringify(rules, { lineWidth: 0 })
}
