import { describe, expect, test } from "vitest"

import { generateManifest, idPrefix } from "../../scripts/manifest"
import { createProject } from "../helpers/project"

describe("idPrefix", () => {
  test("rules-general is unprefixed; other packages prefix their name", () => {
    expect(idPrefix("rules-general")).toBe("")
    expect(idPrefix("rules-python")).toBe("python/")
    expect(idPrefix("rules-react-native")).toBe("react-native/")
    expect(() => idPrefix("rulecast")).toThrow("rulecast is not a rule package")
  })
})

describe("generateManifest", () => {
  test("merges rule packages in name order, prefixes ids and aliases, rewrites @ paths", async () => {
    const root = await createProject({
      "packages/rules-python/rules.yaml": [
        "- id: no-print",
        "  name: No print",
        "  alias: no-print-in-scripts",
        "  files: '\\.py$'",
        "  detect: { regex: { pattern: 'print\\(' } }",
        '  message: "{{file}}:{{line}} prints."',
        "  context:",
        '    - "@docs/logging.md#levels"',
        '    - { path: "@docs/style.md", mode: read }',
        "",
      ].join("\n"),
      "packages/rules-general/rules.yaml": [
        "# Comments in package files are not copied.",
        "- id: generated-code",
        "  name: Generated code",
        "  stages: [touch]",
        '  context: ["@generated.md"]',
        "",
      ].join("\n"),
      "packages/rulecast/package.json": "{}\n",
      "packages/notes/rules.yaml": "not a rule package\n",
    })
    expect(await generateManifest(root)).toBe(
      [
        "# Generated by `pnpm manifest` from packages/rules-*/rules.yaml. Do not edit by hand.",
        "",
        "- id: generated-code",
        "  name: Generated code",
        "  stages:",
        "    - touch",
        "  context:",
        '    - "@packages/rules-general/generated.md"',
        "- id: python/no-print",
        "  name: No print",
        "  alias: python/no-print-in-scripts",
        "  files: \\.py$",
        "  detect:",
        "    regex:",
        "      pattern: print\\(",
        '  message: "{{file}}:{{line}} prints."',
        "  context:",
        '    - "@packages/rules-python/docs/logging.md#levels"',
        '    - path: "@packages/rules-python/docs/style.md"',
        "      mode: read",
        "",
      ].join("\n"),
    )
  })

  test("rejects a package file that is not a list of rules with ids", async () => {
    const notList = await createProject({ "packages/rules-bad/rules.yaml": "a: 1\n" })
    await expect(generateManifest(notList)).rejects.toThrow("packages/rules-bad/rules.yaml: must be a list of rules")
    const noId = await createProject({ "packages/rules-bad/rules.yaml": "- name: x\n" })
    await expect(generateManifest(noId)).rejects.toThrow("packages/rules-bad/rules.yaml: rule 1 has no id")
  })
})
